export default {
    FETCH_CATEGORIES: 'FETCH_CATEGORIES',
    FETCH_RANDOM: 'FETCH_RANDOM',
    FETCH_NAME: 'FETCH_NAME',
    FETCH_DETAILS: 'FETCH_DETAILS',
    FETCH_BY_INGREDIENT: 'FETCH_INGREDIENT',
    FETCH_INGREDIENTS: 'FETCH_INGREDIENTS'
}
